name: Docker Push kafka-alert-exporter image

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_REPO: ${{ github.repository }}  # z.B. "D4rkiiee/autocon3-ws-a3"
  IMAGE_TAG: v1

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker Login
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" \
            | docker login ${{ env.REGISTRY }} \
              --username ${{ github.actor }} \
              --password-stdin

      - name: Prepare lowercase image name
        run: |
          # Repository-Name in Kleinbuchstaben transformieren
          IMAGE_NAME_LOWER=$(echo "${{ env.IMAGE_REPO }}" | tr '[:upper:]' '[:lower:]')
          # Kompletten Image-Name mit Tag in die Umgebungsvariablen schreiben
          echo "IMAGE_NAME_LOWER=${IMAGE_NAME_LOWER}:${{ env.IMAGE_TAG }}" >> $GITHUB_ENV

      - name: Docker Build
        working-directory: lab2/kafka-alarm-sim
        run: |
          docker build \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }} \
            -f Dockerfile.kafka-alert-exporter \
            .

      - name: Docker Push
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}
